### ISSUE TITLE
Hierarchy is not preserved

### ISSUE THREAD

**Issue by fleity** [TiliSleepStealer/blender-addon-fbx-bundle#4]
When exported using the add on all child objects are parent directly under the root transform object instead of keeping the hierarchy. 
This is important if you would want to animate some parts inside of unity for example. Think a door, frame and handle. Handle is parented to the door, rotate the door taking the handle with it.

**Comment by TiliSleepStealer** [comment]
Correct me If I am wrong, but this addon has never really supported animations in the past? I don't think it will now.

**Comment by fleity** [comment]
Sorry, I found the repo here through google and added the issue before realizing it is a fork. 
I started implementing the functionality on my own though and I believe it nearly works. 
Thanks for the porting the add on to 2.8 :)
